FROM openjdk:11
EXPOSE 8080
ADD ./build/libs/ariaz2699/spring-gumball:v0.0.1-SNAPSHOT.jar /srv/ariaz2699/spring-gumball:v0.0.1-SNAPSHOT.jar
CMD java -jar /srv/ariaz2699/spring-gumball:v0.0.1-SNAPSHOT.jar